### PR TITLE
basic compatibility with sodium 0.5.0+

### LINKED ISSUE #197: incompatible with sodium 0.5
game crashes with sodium 0.5 and latest bobby

### PR DESCRIPTION
**Pull request by noah1510**
This is a temporary fix to get the mod to work with sodium 0.5.0.

~I didn't test with older version of sodium, they might be broken now.~ Sodium 0.4 works since e3209c5930818969d72c0bec3e32890fb347b073
~At the moment the fake chunks probably don't have lighting.~ Basic lighting is added in fb9e958b12eba6e949f335e7284f80ceead01e72

At the moment there is a lot of flickering with the bobby fake chunks.
This is mostly only visible if the server render distance is lower that 8 chunks and you are flying backwards in creative.
On most servers when playing in survival this will work without any rendering problems being noticed by the player.
This is likely caused by unloading Neighbor chunks in sodium and then adding them in bobby again.

Additional help with this would be nice.
kind of fixes #197 .

### CODE REVIEW

**Comment by davepusey** [comment]
No more errors, but render distance very limited to only 8 chunks radius now.

**Comment by SteveKunG** [comment]
This is not the right way to update along with new Sodium. Using reflection with mixins is a bad idea.

`onChunkLightAdded` it seems got removed completely. And after update to support Sodium there are issues with chunk rendering when you moving around. This is huge Sodium changes!

Also here if you want to look at my fork. Feel free to merge into your branch.
https://github.com/SteveKunG/bobby/tree/sodium-0.5

**Comment by noah1510** [comment]
> This is not the right way to update along with new Sodium. Using reflection with mixins is a bad idea.

I have no clue about java programming but that sounds reasonable.
Do you mind if I manually port parts of your code into my fork?
I don't think its useful to bump the version of every dependency.
Also With your design it should be possible to keep support for sodium 0.4 by adding an else to the instanceOf check or am I wrong about that?

**Comment by Altirix** [comment]
had a fairly similar branch to @SteveKunG, i personally looked at just setting the chunk lighting in ChunkTrackerHolder. not having lighting data is what causes bobby chunks to not load correctly after the first world join.

however, this has a few issues, while bobby chunks would now reliably load chunks when moving, real chunks unloading would cause neighbor chunks to also unload, at some point i did have some real chunks load in with no lighting but cant remember if any changes i tried stopped that or not.

i suspect the former issue you would need to prevent neighbor chunks from entering the unloadQueue

https://github.com/Altirix/bobby/tree/very-scuffed-sodium-0.5-test

image

**Comment by noah1510** [comment]
I implemented the suggested improvements by @Altirix and @SteveKunG.
The lighting works good enough.
The replacement of chunks just causes some flickering.

**Comment by noah1510** [comment]
I used the latest version on a server with server render distance of 8 chunks and a client distance of 32 chunks for a few hours.
Walking around I didn't notice the flickering at all even tough I was looking for it.
This might only be a problem when traveling fast (flying, riding boat, minecart,...).

The lighting in bobby chunks looks a bit off, at least when using a shader.
I think the shaders are not properly applied to the bobby chunks since their lightmaps are not correctly calculated or something along those lines.
In addition to that there seems to be a bit of a rendering problem with water chunks.
For a lot of them there is a visible border between the chunks and it is possible to see the water from the side as if there was a really small layer of air in between them.
Both of these lighting things might be effects caused by the same faulty implementation of the onChunkLightAdded function.

**Comment by Firestar99** [comment]
I made a fork of this PR to add a few improvements myself: https://github.com/Firestar99/bobby

> This is not the right way to update along with new Sodium. Using reflection with mixins is a bad idea.

cb13263c49233700e56adcbfe42b8297691b94ec replaces reflection (and the continuous lookups of methods) with MethodHandles and invokeDynamic. When you use Lambdas the Java Compiler will also use these, so they should be as performant as lambdas. Sadly I don't know a thing of Mixins (or modern mc modding) so these could provide an even better solution.
Tested with Sodium 0.4, 0.5 and without.

803df1970be51bbe29299f0cd9beefff1b93cfc8 adds `sodiumVersionRuntime` to `gradle.properties` so you can easily test with both versions by just uncommenting them

**Comment by noah1510** [comment]
> https://github.com/Johni0702/bobby/commit/803df1970be51bbe29299f0cd9beefff1b93cfc8 adds sodiumVersionRuntime to gradle.properties so you can easily test with both versions by just uncommenting them (but it will always compile with sodium 0.5)

I just had two folders and used a symlink. That also worked fine and does not need to add actual dependencies.

> https://github.com/Johni0702/bobby/commit/cb13263c49233700e56adcbfe42b8297691b94ec replaces reflection

Is it possible to use lambda functions instead of the Sodium05Compatability class?
If that class exists there might as well be a mixin like I did in my first iteration.
I don't know the lambda function syntax in java, I only know how they work in C++ 😅 

I will look into adapting your suggestions 👍🏻

**Comment by noah1510** [comment]
@SteveKunG @Firestar99 do you think using methodHandles work better together with mixins or is that just reflections but with extra steps.
If MethodHandles are a proper way to interact with mixins then going back to my first implementation would simplify a lot of the code and get rid of the version checks.

**Comment by Firestar99** [comment]
Your Implementation looks good, just some small (maybe nick picky) comments:
* the type `chunkFunctionInterface` should be PasCalCase by Java Convention
* in my version I isolated Sodium 0.5 support to a separate class, don't know if that's really an advantage, not like we'll compile against 0.4 again
* your version is technically slower with sodium 0.4 as you have a double redirection (lambda then Methodhandle) compared to 1 redirection I had, but let's be honest it's not on the hot path so who cares

For context on MethodHandles: they are effectively a replacement for reflection where all validation is front-loaded to the construction of the MethodHandle, so that invocation won't need to do any validation and thus will be fast, compared to the reflection API. But this also requires some weird non-Java things, like you needing to match the return type by casting it otherwise it will fail. Thus most won't ever use this API and will opt for the simpler and slower reflection, which uses MethodHandles in the background. Though I think the most useful part are VarHandles as you can do C++ acquire/release atomic operations on them.

Lambdas pretty much don't expose any MethodHandle stuff, as the compiler just generates it. In fact lambdas are handled by creating a synthetic method containing their code, creating a MethodHandle to that method in the static init block, and when the lambda is constructed use LambdaMetaFactory with that MethodHandle and any values / object references you want to pass to construct the lambda. Dynamic languages in the JVM may also use these systems to accelerate dynamic method calls, but anyways the end user will never see any of this stuff.

**Comment by noah1510** [comment]
@Firestar99 Thanks for the feedback.
I did another rework since I still was not happy with how the code worked and looked.
Now its closer to your suggested implementation however it has a lot of duplication removed.

I also raised the version number to make it easier to see that a new (development) version is loaded.

For #197:
[This is the new file: bobby-5.1.0-dev.tar.gz](https://github.com/Johni0702/bobby/files/12313618/bobby-5.1.0-dev.tar.gz)

**Comment by Stephen5311** [comment]
@noah1510 Hey, I just tested the latest file, seems like chunks still flicker/reload when you pass into a new chunk. It might only be at higher Y levels where this occurs (or maybe only where terrain goes higher up?)... Maybe Y ~160 or higher? Tested with shaders too and same thing happens. Otherwise I'm getting a 10-15% FPS increase with Sodium 5.0 and Bobby RD @ 64 so is an improvement. 👍

**Comment by noah1510** [comment]
That was never fixed and it does not seem trivial to do so. The only chunks that should flicker are those being unloaded. In my experience when playing in survival where you done move backwards that much and fast I did notice very little flickering. It is also more noticeable the lower the server render distance is since you often done see the chunks that are being unloaded.

**Comment by noah1510** [comment]
I opened an issue in sodium where I requested help with the compatibility.
Basically all that needs to happen is for the folks at sodium to add something that allows disabling the ClientChunkManagerMixin in sodium.
They added that to their planned things for sodium 0.5.1 and once it exists this can finally be marked as resolved.

I will add a warning to discourage the use of bobby with sodium 0.5.0, but not add that version to breaks since it does not break but only has some visual problems.

**Comment by davepusey** [comment]
For the record, I'm still using the version from https://github.com/Johni0702/bobby/issues/197#issuecomment-1668393415 without any apparent issues. This is in conjunction with Iris 1.6.5 and shaders Complementary 4.7.2

**Comment by noah1510** [comment]
If you want backwards you should see some chunks glitching when playing on a server.
This is because the chunks are being unloaded and then loaded back in again.
The lower the server render distance the more noticeable this is.
When not looking for it I was not noticing it most of the time either but that is a know regression with a known solution.

**Comment by Altirix** [comment]
https://github.com/Altirix/bobby/commit/a4535a4fd4f4f9e87a316f7b35a10ad67e1091c4

we just need to cancel the unload method before sodiums unload hook, given it should not be aware of chunks being replaced. if they dont get replaced sodium should work as normal

**Comment by noah1510** [comment]
I just implemented and tested your changes against both sodium 0.4 and 0.5 and they seem to work in both cases.
Would the problem with chunks being available too early be fixed by cancelling the `ClientChunkManagerMixin.onChunkLoaded` function in a similar way to what was done to the onChunkUnloaded function?

There are still some cases where I notice render problems when using bobby with sodium 0.5 which are not present with sodium 0.4.
I will try to capture and post a video, to show what I mean.
Playing in survival most of them should not be noticeable.

Here is the latest build: [bobby-5.1.0-dev.tar.gz](https://github.com/Johni0702/bobby/files/12320327/bobby-5.1.0-dev.tar.gz)

**Comment by noah1510** [comment]
After fighting with obs for an hour I managed to capture my problems properly.
The following video is a demonstration of every problem I encountered when running bobby with sodium 0.5.0: https://youtu.be/60snICMh9yE

You can skip the first 30 seconds, I was looking for the problems but just too lazy to cut them out.
For details of the setup look in the description.
I put everything there to make reproducing my problems as easy as possible.

As you can see there is a lot more chunk unloading done than I would expect, especially near the end of the loaded chunks.
This does not happen when using sodium 0.4.x, so another optimization of sodium might need to be worked around.

Also free cam completely break the rendering when leaving loaded chunks but that might be a problem they have to fix.

**Comment by davepusey** [comment]
That's looks very much like extremely slow terrain generation to me. The sort of thing you see when you reach the edge of existing chunks on an overloaded server.

**Comment by Altirix** [comment]
> 

i believe this kinda of chunk not rendering is a vanilla thing, (referring to https://youtu.be/60snICMh9yE?t=39)

i cant remeber where the code for it is atm, but i believe the idea is if theres 1+ empty chunks then chunks behind it will not be rendered.

due to the issue with false positives in sodiums chunk culling prior to 0.5.0 its documented quite well that if 1 chunk is not rendered all chunks behind it will also be not rendered. i have an example of this, and iirc sodium was culling only the first chunk of those missing from this image https://media.discordapp.net/attachments/651120262129123330/900403464528597122/2021-10-20_16.09.12.png?width=1712&height=916

however in this example the cause for those far out chunks not rendering is it because we dont have the chunks cached that let the chunks further out be connected.

**Comment by noah1510** [comment]
> That's looks very much like extremely slow terrain generation to me. The sort of thing you see when you reach the edge of existing chunks on an overloaded server. I've not seen anything like that myself so far.

@davepusey the terrain generation is more than fast enough.
I simply test with a server render distance of 3 chunks.
This causes all bobby related rendering problems to happen faster and be more noticeable since the client render distance is 10 times higher than the server render distance and the border between regular chunks and bobby chunks is close.

> i believe this kinda of chunk not rendering is a vanilla thing,

> i cant remeber where the code for it is atm, but i believe the idea is if theres 1+ empty chunks then chunks behind it will not be rendered. which makes sense, sodium seems to have a slightly diffrent result, but the general optimisation is the same

Well that makes sense if your render distance is the same as the one on the server.
However causing a hole of chunks with no data is easy when you have bobby since you can simply walk a U turn and you might have some chunks that were not loaded.
On reasonable server render distances this is likely not going to be a problem and I did only encounter this on my local testing server since the render distance is that low.

Also I did some more testing with sodium 0.4 and sodium 0.5.
They both do this culling however the culling works more reliable on sodium 0.5 which causes this problem to be easier to notice.
The unloading of chunks on the edge of the screen seems to happen as a result of culling the last node on the edge of the screen.
I just made a few screenshots that illustrate when exactly the unloading happens.
Below is an image to show the conditions that cause the unloading.
I am pretty sure the same happens in the video.

Chunk culling illustartion

**Comment by Johni0702** [comment]
Thanks for all the effort. Unfortunately I fear you've been lead astray by the existing Sodium compatibility code (and I don't at all blame you for it, it's evolved significantly across three different Sodium versions and probably isn't easy to understand at all with how indirect it is).
I've had a look at Sodium 0.5 today and came to the conclusion that almost none of the existing compatibility code is useful any more because a call to Sodium's unload no longer immediately unloads the chunk. So we can without problem let Sodium mark the chunk as unloaded, then simply mark it as loaded immediately after, and the result is as if nothing happened.
After ripping most of the old code out (tried for a while to keep compat with both but I don't want Bobby to grow tech debt if people want to use Bobby with an older version of Sodium, they can use an older version of Bobby), restoring compatibility was almost trivial: https://github.com/Johni0702/bobby/commit/8509a8274d782914b8b333123ef988fedff101e8
I'm left with only two special cases (the onUnload one isn't even new) and one [bug fix](https://github.com/CaffeineMC/sodium-fabric/pull/2001) required in Sodium. And while I haven't yet tested it extensively, a few simple tests didn't bring up any (Sodium-related) issues.

> i believe this kinda of chunk not rendering is a vanilla thing [...]

Yes, it is. All the culling speculation is also correct afaik.
I'm somewhat torn on what to do about it though and was never able to find a satisfying solution. It's probably not too difficult to fix actually, Bobby simply has to load empty chunks for all missing chunks. It does however allow one to see the insides of chunks (as in the left to screenshots; in that case I assume that's caused by improper Sodium compatibility), which is effectively a weak form of xray and there may be servers which take issue with such functionality.
Additionally, it requires all chunks on the border to be re-rendered whenever a new row is received (cause block rendering depends on their immediate neighbors, and those then changed from air to real data). Though thinking about it, that's probably not too big of a concern when you're already using Bobby to increase your render distance, which requires a lot of chunk building too.

**Comment by EGOIST1372** [comment]
ok it seems the issues were causing by sodium extra
now with unofficial bobby v5.1.0 and latest sodium 0.5.1 it works beautifully 👌

**Comment by davepusey** [comment]
Confirming that the version posted here...

https://github.com/Johni0702/bobby/pull/199#issuecomment-1674487420

...works great with Iris 1.6.7 and Sodium 0.5.1

**Comment by boehmseb** [comment]
Testing with the `sodium-0.5` branch, single player worked fine for me, but multiplayer always crashed:
```
java.lang.NullPointerException: Cannot invoke "me.jellysquid.mods.sodium.client.render.chunk.map.ChunkTrackerHolder.sodium$getTracker()" because "world" is null
	at me.jellysquid.mods.sodium.client.render.chunk.map.ChunkTrackerHolder.get(ChunkTrackerHolder.java:7)
	at net.minecraft.class_631.bobby_onFakeChunkAdded(class_631.java:2522)
	at de.johni0702.minecraft.bobby.FakeChunkManager.load(FakeChunkManager.java:298)
	at de.johni0702.minecraft.bobby.FakeChunkManager$LoadingJob.lambda$complete$1(FakeChunkManager.java:409)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at de.johni0702.minecraft.bobby.FakeChunkManager$LoadingJob.complete(FakeChunkManager.java:409)
	at de.johni0702.minecraft.bobby.FakeChunkManager.update(FakeChunkManager.java:251)
	at de.johni0702.minecraft.bobby.FakeChunkManager.update(FakeChunkManager.java:128)
	at net.minecraft.class_310.handler$zbi000$bobby$bobbyUpdate(class_310.java:4028)
	at net.minecraft.class_310.method_1523(class_310.java:1178)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)
```
I'm not really familiar with the mixin library, but it seems like the constructor in `SodiumChunkManagerMixin` never gets called for some reason leaving `world` uninitialized. I was able to work around this by using `ClientChunkManager.getWorld()` instead. Although this seems a bit hacky since it requires casts. Bobby seems to work fine in multiplayer with this fix though.

If someone want's the patch I'm happy to share.

**Comment by Altirix** [comment]
> Testing with the `sodium-0.5` branch, single player worked fine for me, but multiplayer always crashed:
> 
> ```
> java.lang.NullPointerException: Cannot invoke "me.jellysquid.mods.sodium.client.render.chunk.map.ChunkTrackerHolder.sodium$getTracker()" because "world" is null
> 	at me.jellysquid.mods.sodium.client.render.chunk.map.ChunkTrackerHolder.get(ChunkTrackerHolder.java:7)
> 	at net.minecraft.class_631.bobby_onFakeChunkAdded(class_631.java:2522)
> 	at de.johni0702.minecraft.bobby.FakeChunkManager.load(FakeChunkManager.java:298)
> 	at de.johni0702.minecraft.bobby.FakeChunkManager$LoadingJob.lambda$complete$1(FakeChunkManager.java:409)
> 	at java.base/java.util.Optional.ifPresent(Optional.java:178)
> 	at de.johni0702.minecraft.bobby.FakeChunkManager$LoadingJob.complete(FakeChunkManager.java:409)
> 	at de.johni0702.minecraft.bobby.FakeChunkManager.update(FakeChunkManager.java:251)
> 	at de.johni0702.minecraft.bobby.FakeChunkManager.update(FakeChunkManager.java:128)
> 	at net.minecraft.class_310.handler$zbi000$bobby$bobbyUpdate(class_310.java:4028)
> 	at net.minecraft.class_310.method_1523(class_310.java:1178)
> 	at net.minecraft.class_310.method_1514(class_310.java:802)
> 	at net.minecraft.client.main.Main.main(Main.java:250)
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
> 	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
> 	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
> 	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
> 	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
> 	at org.polymc.EntryPoint.main(EntryPoint.java:74)
> ```
> 
> I'm not really familiar with the mixin library, but it seems like the constructor in `SodiumChunkManagerMixin` never gets called for some reason leaving `world` uninitialized. I was able to work around this by using `ClientChunkManager.getWorld()` instead. Although this seems a bit hacky since it requires casts. Bobby seems to work fine in multiplayer with this fix though.
> 
> If someone want's the patch I'm happy to share.

yeah, i found this too, i have a fix ill pr in

**Pull request closed without merging**
